{{- if .Values.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "proxysql-operator.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "proxysql-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: [leases]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "proxysql-operator.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "proxysql-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "proxysql-operator.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "proxysql-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
