apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxysql-cluster.fullname" . }}
  labels:
    {{- include "proxysql-cluster.labels" . | nindent 4 }}
data:
  proxysql.cnf: |
{{ tpl (.Files.Get "files/proxysql.cnf") . | indent 4 }}
