{{- $pw := fromYaml (include "proxysql-cluster.passwords" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxysql-cluster.fullname" . }}
  labels:
    {{- include "proxysql-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password:   {{ $pw.admin   | b64enc | quote }}
  radmin-password:  {{ $pw.radmin  | b64enc | quote }}
  monitor-password: {{ $pw.monitor | b64enc | quote }}
