apiVersion: v1
kind: Namespace
metadata:
  name: percona-pxc-demo
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster1-secrets
  namespace: percona-pxc-demo
stringData:
  root: "REPLACE-ME-root"
  xtrabackup: "REPLACE-ME-xtrabackup"
  monitor: "REPLACE-ME-monitor"
  operator: "REPLACE-ME-operator"
  proxyadmin: "REPLACE-ME-proxyadmin"
  replication: "REPLACE-ME-replication"
---
apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: cluster1
  namespace: percona-pxc-demo
spec:
  secretsName: cluster1-secrets
  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0.39-30.1
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 5Gi
  # We're providing our own ProxySQL via the operator — disable Percona's.
  haproxy:
    enabled: false
  proxysql:
    enabled: false
