apiVersion: proxysql.com/v1alpha1
kind: ProxySQLCluster
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: proxysqlcluster-sample
spec:
  # TODO(user): Add fields here
